# Generated by Django 6.0.5 on 2026-05-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField(verbose_name='Ulasan / Feedback')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mobil', models.CharField(max_length=100, verbose_name='Nama Mobil')),
                ('merek', models.CharField(max_length=50)),
                ('harga_per_hari', models.IntegerField(verbose_name='Harga per Hari (Rp)')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('disewa', 'Sedang Disewa')], default='tersedia', max_length=20)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('gambar_url', models.URLField(blank=True, help_text='Masukkan URL foto mobil dari internet', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('nomor_hp', models.CharField(max_length=15, verbose_name='Nomor WhatsApp')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Sewa')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai Sewa')),
                ('total_harga', models.IntegerField(blank=True, null=True)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='rental.mobil')),
            ],
        ),
    ]
