# Generated by Django 6.0.5 on 2026-05-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamuPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pesan', models.TextField(verbose_name='Kritik / Saran Rental')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesananPS',
            fields=[
                ('id_sewa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sewa')),
                ('nama_penyewa', models.CharField(max_length=100, verbose_name='Nama Penyewa')),
                ('no_hp', models.CharField(max_length=15, verbose_name='Nomor HP/WhatsApp')),
                ('tanggal_sewa', models.DateField(verbose_name='Tanggal Sewa')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('lama_main', models.IntegerField(verbose_name='Lama Main (Jam)')),
                ('total_bayar', models.IntegerField(blank=True, null=True, verbose_name='Total Bayar')),
                ('status_pembayaran', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Lunas', 'Lunas')], default='Belum Bayar', max_length=20, verbose_name='Status Pembayaran')),
            ],
        ),
        migrations.CreateModel(
            name='PSUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_ps', models.CharField(max_length=10, verbose_name='Nomor Unit PS (Contoh: PS-01)')),
                ('tipe_ps', models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5')], max_length=10, verbose_name='Tipe PS')),
                ('harga_per_jam', models.IntegerField(verbose_name='Harga per Jam (Rp)')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipakai', 'Sedang Dimainkan')], default='tersedia', max_length=20)),
                ('gambar_url', models.URLField(blank=True, help_text='Masukkan URL gambar console PS dari internet', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BukuTamu',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='mobil',
        ),
        migrations.AddField(
            model_name='pesananps',
            name='ps_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ps', to='rental.psunit'),
        ),
        migrations.DeleteModel(
            name='Mobil',
        ),
        migrations.DeleteModel(
            name='Pesanan',
        ),
    ]
