# Generated by Django 6.0.5 on 2026-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_bukutamups_pesananps_psunit_delete_bukutamu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesananps',
            name='metode_pembayaran',
            field=models.CharField(choices=[('Cash / Tunai', 'Cash / Tunai'), ('QRIS / Dana / Gopay', 'QRIS / Dana / Gopay'), ('Transfer Bank', 'Transfer Bank')], default='Cash / Tunai', max_length=30, verbose_name='Metode Pembayaran'),
        ),
    ]
