# Generated by Django 6.0.5 on 2026-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_pesananps_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananps',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Selesai'),
        ),
        migrations.AlterField(
            model_name='psunit',
            name='gambar_url',
            field=models.URLField(blank=True, help_text='URL gambar console dari internet', null=True),
        ),
        migrations.AlterField(
            model_name='psunit',
            name='nomor_ps',
            field=models.CharField(max_length=10, verbose_name='Nomor Unit PS'),
        ),
    ]
