# Generated by Django 5.1.4 on 2026-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_pesananps_jam_selesai_alter_psunit_gambar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psunit',
            name='tipe_ps',
            field=models.CharField(choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PS6', 'PlayStation 6')], max_length=10, verbose_name='Tipe PS'),
        ),
    ]
