# Generated by Django 5.1.4 on 2026-05-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_psunit_tipe_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamups',
            name='is_disematkan',
            field=models.BooleanField(default=False, verbose_name='Sematkan di Paling Atas (Pin Comment)'),
        ),
        migrations.AddField(
            model_name='bukutamups',
            name='jumlah_voting',
            field=models.IntegerField(default=0, verbose_name='Jumlah Vote Suka'),
        ),
        migrations.AddField(
            model_name='bukutamups',
            name='kategori',
            field=models.CharField(choices=[('Kritik / Saran', 'Kritik / Saran'), ('Request Game Baru', 'Request Game Baru'), ('Cari Lawan Mabar', 'Cari Lawan Mabar')], default='Kritik / Saran', max_length=30, verbose_name='Kategori Kiriman'),
        ),
        migrations.AddField(
            model_name='bukutamups',
            name='nama_game_request',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Judul Game (Khusus Request Game)'),
        ),
        migrations.AlterField(
            model_name='bukutamups',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Gamers'),
        ),
        migrations.AlterField(
            model_name='bukutamups',
            name='pesan',
            field=models.TextField(verbose_name='Isi Pesan / Tantangan Mabar'),
        ),
    ]
