# Generated by Django 5.1.4 on 2026-05-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_bukutamups_is_disematkan_bukutamups_jumlah_voting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOperator',
            fields=[
                ('id_shift', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_buka', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Buka Shift')),
                ('waktu_tutup', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Tutup Shift')),
                ('modal_awal', models.IntegerField(verbose_name='Modal Awal Laci (Rp)')),
                ('uang_fisik_akhir', models.IntegerField(blank=True, null=True, verbose_name='Uang Fisik Akhir di Laci (Rp)')),
                ('total_pendapatan_sistem', models.IntegerField(default=0, verbose_name='Pendapatan via Sistem (Rp)')),
                ('status', models.CharField(choices=[('Buka', 'Buka'), ('Tutup', 'Tutup')], default='Buka', max_length=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
        ),
    ]
